version: '3.8'

services:
    postgres:
        ports: -5432:5432
        environment:
            - POSTGRES_PASSWORD=password
    user_app:
        build:
            context: ./
            dockerFile: dockerFile
